import hashlib
import re
import sys
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set, Tuple

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


def safe_print(msg: str) -> None:
    try:
        print(msg)
    except Exception:
        try:
            print(msg.encode("ascii", "replace").decode("ascii"))
        except Exception:
            pass


class RecoveryEngine:
    """
    NR AI Code Reasoning & Recovery Engine.

    Takes error diagnostics + source code, reasons about the root cause,
    generates targeted minimal patches, and applies bounded retry loops
    with cycle detection and automatic rollback capabilities.
    """

    def __init__(self, max_retries: int = 3):
        self.max_retries = max_retries
        self.patch_history: Set[str] = set()
        self.custom_ai_reasoner: Optional[Callable[[Dict[str, Any], str], Optional[str]]] = None

    def set_custom_reasoner(
        self, reasoner_fn: Callable[[Dict[str, Any], str], Optional[str]]
    ) -> None:
        """Attach an external AI or LLM reasoning model for complex code repair."""
        self.custom_ai_reasoner = reasoner_fn

    def reset_history(self) -> None:
        self.patch_history.clear()

    def generate_fix(
        self,
        error_info: Dict[str, Any],
        source_code: str,
        filename: str = "",
    ) -> Dict[str, Any]:
        """
        Reason about the error and return a proposed patch.

        Returns:
            {
                "success": bool,
                "strategy": str,
                "fixed_code": str,
                "description": str,
                "confidence": float,
            }
        """
        if not source_code:
            return {
                "success": False,
                "strategy": "none",
                "fixed_code": source_code,
                "description": "Source code is empty.",
                "confidence": 0.0,
            }

        # 1. If custom AI reasoner is attached, try it first
        if self.custom_ai_reasoner:
            try:
                ai_fix = self.custom_ai_reasoner(error_info, source_code)
                if ai_fix and ai_fix != source_code:
                    return {
                        "success": True,
                        "strategy": "ai_reasoning",
                        "fixed_code": ai_fix,
                        "description": "Applied fix generated by AI reasoning engine.",
                        "confidence": 0.95,
                    }
            except Exception as e:
                safe_print(f"⚠️ AI reasoner failed: {e}")

        # 2. Rule & Heuristic Reasoning Engine
        language = error_info.get("language", "python")
        error_type = error_info.get("type", "")
        line_num = error_info.get("line")
        message = error_info.get("message", "")

        fixed_code = None
        description = ""
        strategy = "rule_based"

        if language == "python":
            fixed_code, description = self._recover_python(
                error_type, line_num, message, source_code
            )
        elif language == "java":
            fixed_code, description = self._recover_java(
                error_type, line_num, message, source_code, filename
            )
        elif language == "javascript":
            fixed_code, description = self._recover_javascript(
                error_type, line_num, message, source_code
            )
        elif language == "c":
            fixed_code, description = self._recover_c(
                error_type, line_num, message, source_code
            )

        if fixed_code and fixed_code != source_code:
            # Check for cycle/oscillating fixes
            code_hash = hashlib.md5(fixed_code.encode("utf-8")).hexdigest()
            if code_hash in self.patch_history:
                return {
                    "success": False,
                    "strategy": "cycle_detected",
                    "fixed_code": source_code,
                    "description": "Recovery cycle detected: This fix was already attempted.",
                    "confidence": 0.0,
                }

            self.patch_history.add(code_hash)
            return {
                "success": True,
                "strategy": strategy,
                "fixed_code": fixed_code,
                "description": description,
                "confidence": 0.9,
            }

        return {
            "success": False,
            "strategy": "unresolved",
            "fixed_code": source_code,
            "description": f"No automatic recovery rule matched {error_type} in {language}.",
            "confidence": 0.0,
        }

    # -------------------------------------------------
    # PYTHON RECOVERY RULES
    # -------------------------------------------------

    def _recover_python(
        self,
        error_type: str,
        line_num: Optional[int],
        message: str,
        code: str,
    ) -> Tuple[Optional[str], str]:
        lines = code.splitlines()
        total_lines = len(lines)

        # 1. Indentation Errors
        if error_type in ["IndentationError", "TabError"]:
            fixed_lines = []
            indent_level = 0
            for raw_line in lines:
                stripped = raw_line.strip()
                if not stripped:
                    fixed_lines.append("")
                    continue

                # Dedent if starts with elif, else, except, finally
                if re.match(r"^(elif|else|except|finally):", stripped):
                    curr_indent = max(0, indent_level - 1)
                else:
                    curr_indent = indent_level

                fixed_lines.append("    " * curr_indent + stripped)

                # Next indent level
                if stripped.endswith(":"):
                    indent_level = curr_indent + 1
                elif stripped in ["return", "break", "continue", "pass", "raise"]:
                    # May dedent
                    pass

            return "\n".join(fixed_lines) + "\n", "Normalized indentation across all blocks."

        # 2. Syntax Errors
        if error_type == "SyntaxError":
            if line_num and 1 <= line_num <= total_lines:
                idx = line_num - 1
                target_line = lines[idx]

                # Missing colon on control statement
                if "expected ':'" in message or "invalid syntax" in message:
                    clean_line = target_line.rstrip()
                    if re.search(
                        r"^\s*(def\s+\w+\(.*\)|class\s+\w+.*|if\s+.*|elif\s+.*|else|for\s+.*|while\s+.*|try|except.*|finally|with\s+.*)",
                        clean_line,
                    ) and not clean_line.endswith(":"):
                        lines[idx] = clean_line + ":"
                        return "\n".join(lines) + "\n", f"Appended missing ':' at line {line_num}."

                # Python 2 print statement: print "..." -> print("...")
                p2_match = re.match(r'^(\s*)print\s+([\'"].*[\'"])\s*$', target_line)
                if p2_match:
                    indent, content = p2_match.group(1), p2_match.group(2)
                    lines[idx] = f"{indent}print({content})"
                    return "\n".join(lines) + "\n", f"Updated legacy print statement to Python 3 syntax at line {line_num}."

                # Unterminated string quote
                if "unterminated string literal" in message or "EOL while scanning" in message:
                    if target_line.count('"') % 2 != 0:
                        lines[idx] = target_line + '"'
                        return "\n".join(lines) + "\n", f"Closed unterminated double quote at line {line_num}."
                    elif target_line.count("'") % 2 != 0:
                        lines[idx] = target_line + "'"
                        return "\n".join(lines) + "\n", f"Closed unterminated single quote at line {line_num}."

                # Missing closing parenthesis/bracket
                open_p = target_line.count("(") - target_line.count(")")
                if open_p > 0:
                    lines[idx] = target_line + (")" * open_p)
                    return "\n".join(lines) + "\n", f"Added missing closing parenthesis at line {line_num}."

        # 3. NameError (Missing standard imports)
        if error_type == "NameError":
            match = re.search(r"name '([^']+)' is not defined", message)
            if match:
                var = match.group(1)
                std_libs = {
                    "math": "import math",
                    "sys": "import sys",
                    "os": "import os",
                    "json": "import json",
                    "re": "import re",
                    "time": "import time",
                    "random": "import random",
                    "Path": "from pathlib import Path",
                    "datetime": "from datetime import datetime",
                }
                if var in std_libs and std_libs[var] not in code:
                    return std_libs[var] + "\n" + code, f"Added missing import '{std_libs[var]}' for {var}."

        # 4. ZeroDivisionError
        if error_type == "ZeroDivisionError" and line_num and 1 <= line_num <= total_lines:
            idx = line_num - 1
            line = lines[idx]
            # If line is `a / b` or similar, check denominator
            if "/" in line:
                indent_match = re.match(r"^(\s*)", line)
                indent = indent_match.group(1) if indent_match else ""
                guarded = (
                    f"{indent}try:\n"
                    f"{indent}    {line.strip()}\n"
                    f"{indent}except ZeroDivisionError:\n"
                    f"{indent}    print('Error: Division by zero avoided.')"
                )
                lines[idx] = guarded
                return "\n".join(lines) + "\n", f"Added ZeroDivisionError safety guard at line {line_num}."

        return None, ""

    # -------------------------------------------------
    # JAVA RECOVERY RULES
    # -------------------------------------------------

    def _recover_java(
        self,
        error_type: str,
        line_num: Optional[int],
        message: str,
        code: str,
        filename: str,
    ) -> Tuple[Optional[str], str]:
        lines = code.splitlines()
        total_lines = len(lines)

        # 1. Missing semicolon
        if "';' expected" in message and line_num and 1 <= line_num <= total_lines:
            idx = line_num - 1
            line = lines[idx].rstrip()
            if not line.endswith(";") and not line.endswith("{") and not line.endswith("}"):
                lines[idx] = line + ";"
                return "\n".join(lines) + "\n", f"Added missing ';' at line {line_num}."

        # 2. Public class / filename mismatch
        # class Test is public, should be declared in a file named Test.java
        if "should be declared in a file named" in message or (filename and filename.endswith(".java")):
            expected_class = Path(filename).stem if filename else ""
            if expected_class:
                new_code = re.sub(
                    r"public\s+class\s+([A-Za-z0-9_]+)",
                    f"public class {expected_class}",
                    code,
                    count=1,
                )
                if new_code != code:
                    return new_code, f"Renamed public class to match filename '{expected_class}'."

        return None, ""

    # -------------------------------------------------
    # JAVASCRIPT RECOVERY RULES
    # -------------------------------------------------

    def _recover_javascript(
        self,
        error_type: str,
        line_num: Optional[int],
        message: str,
        code: str,
    ) -> Tuple[Optional[str], str]:
        lines = code.splitlines()
        total_lines = len(lines)

        if line_num and 1 <= line_num <= total_lines:
            idx = line_num - 1
            line = lines[idx]

            # Missing closing parenthesis or bracket
            open_p = line.count("(") - line.count(")")
            if open_p > 0:
                lines[idx] = line.rstrip() + (")" * open_p) + (";" if not line.rstrip().endswith(";") else "")
                return "\n".join(lines) + "\n", f"Added missing closing parenthesis at JS line {line_num}."

            # ReferenceError: missing declaration e.g. x is not defined
            ref_match = re.search(r"ReferenceError:\s*(\w+)\s+is not defined", message)
            if ref_match:
                var_name = ref_match.group(1)
                indent_match = re.match(r"^(\s*)", line)
                indent = indent_match.group(1) if indent_match else ""
                lines.insert(idx, f"{indent}let {var_name} = null;")
                return "\n".join(lines) + "\n", f"Declared missing variable '{var_name}' before line {line_num}."

        return None, ""

    # -------------------------------------------------
    # C RECOVERY RULES
    # -------------------------------------------------

    def _recover_c(
        self,
        error_type: str,
        line_num: Optional[int],
        message: str,
        code: str,
    ) -> Tuple[Optional[str], str]:
        lines = code.splitlines()
        total_lines = len(lines)

        # 1. Missing semicolon
        if "expected ';'" in message and line_num and 1 <= line_num <= total_lines:
            idx = line_num - 1
            line = lines[idx].rstrip()
            if not line.endswith(";") and not line.endswith("{") and not line.endswith("}"):
                lines[idx] = line + ";"
                return "\n".join(lines) + "\n", f"Added missing ';' at C line {line_num}."

        # 2. Missing stdio.h / stdlib.h
        if "printf" in code and "#include <stdio.h>" not in code:
            return "#include <stdio.h>\n" + code, "Added missing '#include <stdio.h>' header."
        if ("malloc" in code or "free" in code) and "#include <stdlib.h>" not in code:
            return "#include <stdlib.h>\n" + code, "Added missing '#include <stdlib.h>' header."

        return None, ""


if __name__ == "__main__":
    safe_print("========================================")
    safe_print("     NR AI RECOVERY ENGINE TEST")
    safe_print("========================================")

    engine = RecoveryEngine(max_retries=3)

    # 1. Python missing colon
    bad_py = "def greet(name)\n    print(f'Hello {name}')\n"
    error_py = {
        "language": "python",
        "type": "SyntaxError",
        "line": 1,
        "message": "SyntaxError: expected ':'",
    }
    fix_py = engine.generate_fix(error_py, bad_py)
    safe_print(f"\n1. Python Fix Result: {fix_py['success']}")
    safe_print(f"Description: {fix_py['description']}")
    safe_print(f"Fixed Code:\n{fix_py['fixed_code']}")

    # 2. Java missing semicolon
    bad_java = (
        "public class App {\n"
        "    public static void main(String[] args) {\n"
        "        int x = 10\n"
        "    }\n"
        "}\n"
    )
    error_java = {
        "language": "java",
        "type": "JavaCompilationError",
        "line": 3,
        "message": "App.java:3: error: ';' expected\n        int x = 10",
    }
    fix_java = engine.generate_fix(error_java, bad_java, filename="App.java")
    safe_print(f"\n2. Java Fix Result: {fix_java['success']}")
    safe_print(f"Description: {fix_java['description']}")
    safe_print(f"Fixed Code:\n{fix_java['fixed_code']}")

    # 3. Python missing standard import
    bad_math = "x = math.sqrt(16)\nprint(x)\n"
    error_math = {
        "language": "python",
        "type": "NameError",
        "line": 1,
        "message": "NameError: name 'math' is not defined",
    }
    fix_math = engine.generate_fix(error_math, bad_math)
    safe_print(f"\n3. Python Import Fix Result: {fix_math['success']}")
    safe_print(f"Description: {fix_math['description']}")
    safe_print(f"Fixed Code:\n{fix_math['fixed_code']}")

    safe_print("\n========================================")
    safe_print("🟢 RECOVERY ENGINE TEST COMPLETE")
    safe_print("========================================")
