"""
NR-AI SkyShield: Security Agent Package.
Step 10 Phase 1 — Security Agent Foundation.
"""

from app.security.agent import DeterministicSecurityGate, SecurityAgent
from app.security.auditor import PermissionAuditor
from app.security.coordinator import SecurityCoordinator
from app.security.models import (
    ApplicationSecurityCard,
    CameraSecurityModel,
    DataVerificationState,
    DeviceSecurityModel,
    EvidenceConfidence,
    FindingCategory,
    MicrophoneSecurityModel,
    PermissionName,
    PermissionStatus,
    SecurityAuditRecord,
    SecurityEvent,
    SecurityFinding,
    SecurityPermission,
    SecurityPolicy,
    SecuritySeverity,
    SecurityState,
    redact_sensitive_data,
)
from app.security.enrollment_models import (
    DEFAULT_PHASE2_CAPABILITIES,
    PROHIBITED_CAPABILITIES,
    AuthorizationState,
    DeviceIdentityModel,
    DeviceKeyRecord,
    DeviceSession,
    EnrollmentState,
    PairingRequest,
    PairingRequestStatus,
    SkyShieldCapability,
    generate_challenge,
    generate_pairing_code,
    mask_phone_number,
    normalize_phone_number,
)
from app.security.pairing_manager import (
    CapabilityEscalationError,
    DevicePairingManager,
    DeviceRevokedError,
    IllegalEnrollmentTransitionError,
)
from app.security.health_models import (
    AnomalyEvent,
    AnomalySeverity,
    DeviceBaseline,
    DeviceHealthSnapshot,
    DeviceHealthState,
    SafeResponseAction,
    SecurityPostureScore,
    TelemetryProcessingState,
    ThreatCategory,
    ThreatConclusion,
)
from app.security.health_analyzer import (
    AUTH_FAILURE_BURST_THRESHOLD,
    CLOCK_SKEW_TOLERANCE_SECONDS,
    CPU_CRITICAL_THRESHOLD,
    CPU_WARNING_THRESHOLD,
    MEMORY_CRITICAL_THRESHOLD,
    MEMORY_WARNING_THRESHOLD,
    STORAGE_CRITICAL_THRESHOLD,
    STORAGE_WARNING_THRESHOLD,
    DeviceHealthAnalyzer,
)
from app.security.incident_models import (
    ActionConfirmationStatus,
    AlertSeverity,
    EvidenceVerificationState,
    HIGH_IMPACT_ACTIONS,
    IncidentState,
    SafeActionProposal,
    SecurityAlert,
    SecurityEvidence,
    SecurityIncident,
    SourceAuthority,
    ThreatAdvisory,
)
from app.security.threat_intelligence import ThreatIntelligenceService
from app.security.safe_response_engine import SafeResponseEngine
from app.security.incident_manager import SecurityIncidentEngine
from app.security.scanner import SecurityScanner

__all__ = [
    "AnomalyEvent",
    "AnomalySeverity",
    "ApplicationSecurityCard",
    "AuthorizationState",
    "CameraSecurityModel",
    "CapabilityEscalationError",
    "DEFAULT_PHASE2_CAPABILITIES",
    "DataVerificationState",
    "DeterministicSecurityGate",
    "DeviceBaseline",
    "DeviceHealthAnalyzer",
    "DeviceHealthSnapshot",
    "DeviceHealthState",
    "DeviceIdentityModel",
    "DeviceKeyRecord",
    "DevicePairingManager",
    "DeviceRevokedError",
    "DeviceSecurityModel",
    "DeviceSession",
    "EnrollmentState",
    "EvidenceConfidence",
    "FindingCategory",
    "IllegalEnrollmentTransitionError",
    "MicrophoneSecurityModel",
    "PROHIBITED_CAPABILITIES",
    "PairingRequest",
    "PairingRequestStatus",
    "PermissionAuditor",
    "PermissionName",
    "PermissionStatus",
    "SafeResponseAction",
    "SecurityAgent",
    "SecurityAuditRecord",
    "SecurityCoordinator",
    "SecurityEvent",
    "SecurityFinding",
    "SecurityPermission",
    "SecurityPolicy",
    "SecurityPostureScore",
    "SecurityScanner",
    "SecuritySeverity",
    "SecurityState",
    "SkyShieldCapability",
    "TelemetryProcessingState",
    "ThreatCategory",
    "ActionConfirmationStatus",
    "AlertSeverity",
    "EvidenceVerificationState",
    "HIGH_IMPACT_ACTIONS",
    "IncidentState",
    "SafeActionProposal",
    "SafeResponseEngine",
    "SecurityAlert",
    "SecurityEvidence",
    "SecurityIncident",
    "SecurityIncidentEngine",
    "SourceAuthority",
    "ThreatAdvisory",
    "ThreatIntelligenceService",
    "generate_challenge",
    "generate_pairing_code",
    "mask_phone_number",
    "normalize_phone_number",
    "redact_sensitive_data",
]
